# This is a basic workflow to help you get started with Actions.

name: Backend CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

  # Triggers the workflow on pull request events targeting the main branch
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the tests for the backend
  test-backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a version that matches your environment

      # 3. Install dependencies and run tests for the backend
      - name: Install backend dependencies and run tests
        run: |
          cd backend
          npm install
          npm test